version: "3"

services:
    robotics:
        image: toto04/robotics:latest
        container_name: robotics
        stdin_open: true # docker run -i
        tty: true # docker run -t
        build: .
        environment:
            - DISPLAY=novnc:0.0
        volumes:
            - /tmp/.X11-unix
            - ./mount:/root/robotics
        command: /bin/bash
    novnc:
        image: theasp/novnc:latest
        container_name: novnc
        ports:
            - "8080:8080"
        environment:
            - DISPLAY_WIDTH=1920
            - DISPLAY_HEIGHT=1080
            - RUN_XTERM=no
networks:
    ros:
        driver: bridge
